[api]
 addr="0.0.0.0:8000"

[redis]
    [redis.default]
       host         = "127.0.0.1:6379"
       db           = "0"
       pwd          = "pwd"
       maxIdle      = 20
       maxActive    = 20
       idleTimeout  = 200
[log]
    path    =   "./logs"
    level   =   "all"
    stdout  =   "true"
    format  =   "{Y-m-d}.log"

[database]
    [database.demo]
        host        = "127.0.0.1"
        port        = "3306"
        prefix      = ""
        user        = "root"
        pass        = "root"
        name        = "demo"
        type        = "mysql"
        tabel       = "hello"
        log         = "true"
    [database.test]
        host        = "127.0.0.1"
        port        = "3306"
        prefix      = ""
        user        = "root"
        pass        = "root"
        name        = "demo"
        type        = "mysql"
        tabel       = "hello"
        log         = "true"
[mq]
    [mq.kafka]
        addr = ["116.62.79.79:9092"]
